// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/google/uuid"
)

type BadRequest struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *BadRequest) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *BadRequest) SetMessage(val string) {
	s.Message = val
}

func (*BadRequest) completeUserRegistrationRes() {}
func (*BadRequest) getAllUsersRes()              {}
func (*BadRequest) loginRes()                    {}
func (*BadRequest) sendEmailVerificationRes()    {}

type BearerAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// CompleteUserRegistrationOK is response for CompleteUserRegistration operation.
type CompleteUserRegistrationOK struct {
	SetCookie string
}

// GetSetCookie returns the value of SetCookie.
func (s *CompleteUserRegistrationOK) GetSetCookie() string {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *CompleteUserRegistrationOK) SetSetCookie(val string) {
	s.SetCookie = val
}

func (*CompleteUserRegistrationOK) completeUserRegistrationRes() {}

type CompleteUserRegistrationReq struct {
	Token    uuid.UUID `json:"token"`
	Email    string    `json:"email"`
	Name     string    `json:"name"`
	Password string    `json:"password"`
}

// GetToken returns the value of Token.
func (s *CompleteUserRegistrationReq) GetToken() uuid.UUID {
	return s.Token
}

// GetEmail returns the value of Email.
func (s *CompleteUserRegistrationReq) GetEmail() string {
	return s.Email
}

// GetName returns the value of Name.
func (s *CompleteUserRegistrationReq) GetName() string {
	return s.Name
}

// GetPassword returns the value of Password.
func (s *CompleteUserRegistrationReq) GetPassword() string {
	return s.Password
}

// SetToken sets the value of Token.
func (s *CompleteUserRegistrationReq) SetToken(val uuid.UUID) {
	s.Token = val
}

// SetEmail sets the value of Email.
func (s *CompleteUserRegistrationReq) SetEmail(val string) {
	s.Email = val
}

// SetName sets the value of Name.
func (s *CompleteUserRegistrationReq) SetName(val string) {
	s.Name = val
}

// SetPassword sets the value of Password.
func (s *CompleteUserRegistrationReq) SetPassword(val string) {
	s.Password = val
}

type Email string

type GetAllUsersOK struct {
	Users []User `json:"users"`
	// Total number of pages.
	TotalPage int `json:"totalPage"`
}

// GetUsers returns the value of Users.
func (s *GetAllUsersOK) GetUsers() []User {
	return s.Users
}

// GetTotalPage returns the value of TotalPage.
func (s *GetAllUsersOK) GetTotalPage() int {
	return s.TotalPage
}

// SetUsers sets the value of Users.
func (s *GetAllUsersOK) SetUsers(val []User) {
	s.Users = val
}

// SetTotalPage sets the value of TotalPage.
func (s *GetAllUsersOK) SetTotalPage(val int) {
	s.TotalPage = val
}

func (*GetAllUsersOK) getAllUsersRes() {}

type ID int64

type InternalServerError struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) sendEmailVerificationRes() {}

// LoginOK is response for Login operation.
type LoginOK struct {
	SetCookie string
}

// GetSetCookie returns the value of SetCookie.
func (s *LoginOK) GetSetCookie() string {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *LoginOK) SetSetCookie(val string) {
	s.SetCookie = val
}

func (*LoginOK) loginRes() {}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *LoginReq) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *LoginReq) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *LoginReq) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *LoginReq) SetPassword(val string) {
	s.Password = val
}

type Name string

type PingOK struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *PingOK) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *PingOK) SetMessage(val string) {
	s.Message = val
}

// SendEmailVerificationOK is response for SendEmailVerification operation.
type SendEmailVerificationOK struct{}

func (*SendEmailVerificationOK) sendEmailVerificationRes() {}

type SendEmailVerificationReq struct {
	Email string `json:"email"`
}

// GetEmail returns the value of Email.
func (s *SendEmailVerificationReq) GetEmail() string {
	return s.Email
}

// SetEmail sets the value of Email.
func (s *SendEmailVerificationReq) SetEmail(val string) {
	s.Email = val
}

type Unauthorized struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Unauthorized) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Unauthorized) SetMessage(val string) {
	s.Message = val
}

func (*Unauthorized) completeUserRegistrationRes() {}
func (*Unauthorized) verifyEmailRes()              {}

// Ref: #/components/schemas/user
type User struct {
	ID    ID    `json:"id"`
	Name  Name  `json:"name"`
	Email Email `json:"email"`
}

// GetID returns the value of ID.
func (s *User) GetID() ID {
	return s.ID
}

// GetName returns the value of Name.
func (s *User) GetName() Name {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() Email {
	return s.Email
}

// SetID sets the value of ID.
func (s *User) SetID(val ID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *User) SetName(val Name) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val Email) {
	s.Email = val
}

type VerifyEmailOK struct {
	Email string `json:"email"`
}

// GetEmail returns the value of Email.
func (s *VerifyEmailOK) GetEmail() string {
	return s.Email
}

// SetEmail sets the value of Email.
func (s *VerifyEmailOK) SetEmail(val string) {
	s.Email = val
}

func (*VerifyEmailOK) verifyEmailRes() {}

type VerifyEmailReq struct {
	Token uuid.UUID `json:"token"`
}

// GetToken returns the value of Token.
func (s *VerifyEmailReq) GetToken() uuid.UUID {
	return s.Token
}

// SetToken sets the value of Token.
func (s *VerifyEmailReq) SetToken(val uuid.UUID) {
	s.Token = val
}
