// Code generated by ogen, DO NOT EDIT.
package api

type CompleteUserRegistrationRes interface {
	completeUserRegistrationRes()
}

type GetAllUsersRes interface {
	getAllUsersRes()
}

type LoginRes interface {
	loginRes()
}

type SendEmailVerificationRes interface {
	sendEmailVerificationRes()
}

type VerifyEmailRes interface {
	verifyEmailRes()
}
