// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package rdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerificationToken struct {
	Token     pgtype.UUID
	Email     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        int64
	Email     string
	Password  string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
